Model: MLP

# Sampling
Sampling: Canonical

N_samples: 64
N_importance_samples: 128


# Function
Function: Sigma

# Loss
Loss: [Color]

# Training
#N_epochs: 30
#lr: 5e-4
#shrink: 100

# Training
N_epochs: 400
lr: 5e-4
shrink: 100