Model: MLP

# Sampling
Sampling: Vanilla
N_samples: 64
N_importance_samples: 64

# Function
Function: Sigma

# Loss
Loss: [Color]

# Training
N_epochs: 15
lr: 0.0005
shrink: 10
# milestones: [10, 20]
# gamma: .5
