Model: MLP

# Sampling
Sampling: Vanilla
N_samples: 64
N_importance_samples: 64

# Function
Function: SDF
speed_factor: 10.
beta_init: 0.1

# loss
Loss: [Color]

# Training
N_epochs: 30
lr: 0.0005
shrink: 10
# milestones: [10, 20]
# gamma: .5
